// Generated by CoffeeScript 1.8.0
var _base;

if ((_base = Array.prototype).compact == null) {
  _base.compact = function() {
    return this.filter(function(item) {
      return item != null;
    });
  };
}
