// Generated by CoffeeScript 1.9.0
var _base, _base1, _base2, _base3, _base4, _base5, _base6, _base7;

if ((_base = Number.prototype).second == null) {
  _base.second = function() {
    return this.seconds();
  };
}

if ((_base1 = Number.prototype).seconds == null) {
  _base1.seconds = function() {
    return this * 1000;
  };
}

if ((_base2 = Number.prototype).minute == null) {
  _base2.minute = function() {
    return this.minutes();
  };
}

if ((_base3 = Number.prototype).minutes == null) {
  _base3.minutes = function() {
    return this.seconds() * 60;
  };
}

if ((_base4 = Number.prototype).hour == null) {
  _base4.hour = function() {
    return this.hours();
  };
}

if ((_base5 = Number.prototype).hours == null) {
  _base5.hours = function() {
    return this.minutes() * 60;
  };
}

if ((_base6 = Number.prototype).day == null) {
  _base6.day = function() {
    return this.days();
  };
}

if ((_base7 = Number.prototype).days == null) {
  _base7.days = function() {
    return this.hours() * 24;
  };
}
