// Generated by CoffeeScript 1.8.0
var _base, _base1;

if ((_base = String.prototype).capitalize == null) {
  _base.capitalize = function() {
    return this[0].toUpperCase() + this.slice(1);
  };
}

if ((_base1 = String.prototype).startsWith == null) {
  _base1.startsWith = function(prefix) {
    return this.indexOf(prefix) === 0;
  };
}
