// Generated by CoffeeScript 1.9.0
var _base, _base1, _base2, _base3;

if ((_base = String.prototype).capitalize == null) {
  _base.capitalize = function() {
    if (!(this.length > 0)) {
      return '';
    }
    return this[0].toUpperCase() + this.slice(1);
  };
}

if ((_base1 = String.prototype).startsWith == null) {
  _base1.startsWith = function(prefix) {
    return this.indexOf(prefix) === 0;
  };
}

if ((_base2 = String.prototype).endsWith == null) {
  _base2.endsWith = function(suffix) {
    return this.indexOf(suffix) === this.length - suffix.length;
  };
}

if ((_base3 = String.prototype).repeat == null) {
  _base3.repeat = function(n) {
    var res, str;
    str = this;
    res = '';
    while (n > 0) {
      if (n & 1) {
        res += str;
      }
      n >>>= 1;
      str += str;
    }
    return res;
  };
}
